### ISSUE TITLE
Running Google Colab notebook provided for Llama 3.2-1B, but nvcc not found

### ISSUE THREAD

**Issue by theoctopusride** [facebookresearch/SpinQuant#15]
Connecting to local runtime in Google Colab with 3090 installed within spinquant conda env using python 3.9.20 on Ubuntu 22.04. Let me know if more info is needed.

Error:
```
Cloning into 'fast-hadamard-transform'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 121 (delta 54), reused 91 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (121/121), 35.86 KiB | 447.00 KiB/s, done.
Resolving deltas: 100% (54/54), done.
Note: switching to '4ea722e434e3d4f2a14522341959ebdbe62be2de'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Processing /home/apps/et_qnn/fast-hadamard-transform
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /home/apps/et_qnn/fast-hadamard-transform/setup.py:77: UserWarning: fast_hadamard_transform was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/apps/et_qnn/fast-hadamard-transform/setup.py", line 111, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined
      
      
      torch.__version__  = 2.3.0
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

nvcc is installed:
```
(spinquant) apps@apps-desktop:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
(spinquant) apps@apps-desktop:~$ nvidia-smi
Tue Oct 22 17:27:28 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:09:00.0  On |                  N/A |
|  0%   42C    P8             20W /  350W |     337MiB /  24576MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1362      G   /usr/lib/xorg/Xorg                            104MiB |
|    0   N/A  N/A      1604      G   /usr/bin/gnome-shell                           79MiB |
|    0   N/A  N/A      3057      G   ...seed-version=20241022-050127.975000        132MiB |
+-----------------------------------------------------------------------------------------+
(spinquant) apps@apps-desktop:~$
```

**Comment by theoctopusride** [comment]
same version of cuda for both nvcc and nvidia-smi doesn't seem to work when initiating jupyter notebook local session inside conda env either
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Sep_12_02:18:05_PDT_2024
Cuda compilation tools, release 12.6, V12.6.77
Build cuda_12.6.r12.6/compiler.34841621_0
...........................................
Tue Oct 22 20:46:58 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:09:00.0  On |                  N/A |
|  0%   50C    P8             24W /  350W |     333MiB /  24576MiB |     25%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1362      G   /usr/lib/xorg/Xorg                            124MiB |
|    0   N/A  N/A      1604      G   /usr/bin/gnome-shell                           75MiB |
|    0   N/A  N/A      3057      G   ...seed-version=20241022-050127.975000        111MiB |
+-----------------------------------------------------------------------------------------+
...........................................
Cloning into 'fast-hadamard-transform'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 121 (delta 54), reused 91 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (121/121), 35.86 KiB | 4.48 MiB/s, done.
Resolving deltas: 100% (54/54), done.
Note: switching to '4ea722e434e3d4f2a14522341959ebdbe62be2de'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Processing /home/apps/et_qnn/fast-hadamard-transform
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /home/apps/et_qnn/fast-hadamard-transform/setup.py:77: UserWarning: fast_hadamard_transform was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/apps/et_qnn/fast-hadamard-transform/setup.py", line 111, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined
      
      
      torch.__version__  = 2.3.0
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by theoctopusride** [comment]
Re-installed Ubuntu 22.04 and used 12.4 Cuda toolkit for nvcc and 12.4 for nvidia drivers / nvidia-smi, generated the consolidated.pth file
